### ISSUE TITLE
CLI delete images command fails

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#615]
**Description:**
After the syntax changes to metadata.json `cellery delete` command fails. A list of existing cell images is returned to during this command and metadata.json of each cells are being read. Hence due to the new changes in metadata.json `cellery delete` command is failing.

**Affected Product Version:**
Latest sdk.
  
**Steps to reproduce:**
1. Build a cell image using `cellery build` command.
2. Delete a cell image using `cellery delete` command.

**Comment by nadundesilva** [comment]
This issue is not related to the structs and the structs had already been properly updated before this issue occurred.

This issue occurred when there are old images present in the repository. This is the expected behavior as the metadata structures were completely changed after the last release.

Therefore, this is not an actual issue and is only the expected behavior.
