### ISSUE TITLE
Move composite sts to cellery-system

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#635]
Currently with composites, the sts for composites starts in the default namespace. It would be better to move this to cellery-system given that the composite-sts is not something the user should be aware of.

**Comment by hasinthaindrajee** [comment]
We had a discussion about this and decided to park without doing change for 0.4.0 release. Below is a note on the discussion.

In order to cater to this we need to restructure the controller loop other than changing the behaviour of STS to cater composite STS as a special case. 

The controller loop has to be modified in a way that, a part of STS resources will be in default namespace (envoyfilter)  whereas the other parts will be in cellery-system namespace (deployment, svc). Currently this is being handled by the controller in a consistent way for both Cells and Composites. When the token service custom resource is created from the controller, the relevant components (envoyfilter, svc, deployment) will be created in the same namespace as per current design. If we do this change we have to change the controller in a way that it will distribute components which are related to STS in different namespaces for Composites whereas in Cells all resources will be in the same namespace.

As an alternative, we can add Composite STS on installation time to cellery-system namespace. This will add an overhead of generating and signing keys from controller keys and passing them to Composite STS at the installation time. This might involve manual work if we change keys after starting the Cellery system.

**Comment by tharindulak** [comment]
Fixed by following PRs
https://github.com/wso2-cellery/mesh-controller/pull/141
https://github.com/wso2-cellery/mesh-security/pull/99
