### ISSUE TITLE
Intermittent error while patching components

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2-cellery/sdk#731]
**Description:**
Below error is getting rarely when trying to patch a component following https://github.com/wso2-cellery/samples/blob/master/docs/pet-store/cell-component-update-and-adv-deployment.md
Observed in GCP full setup

cellery patch pet-be controller --container-image wso2cellery/samples-pet-store-controller:latestv2
❌ Patching component controller in instance pet-be

Unable to patch cell component controller in instance pet-be: unexpected end of JSON input

Since this is an intermittent and rare issue, let's add debug logs which is getting printed to a dedicated file (I think we already have) so that we can debug in the future.

**Comment by hasinthaindrajee** [comment]
Let's just add debug logs if possible.

**Comment by sinthuja** [comment]
I was able to reproduce this for the first time when I patch a component of an instance. For example, I start an instance with name = pet-be, and very first time when I execute the patch command, I got this error; and consecutive attempts succeeded. I again started the pet-be instance with the same name, and didn't encounter the error. 

Then I started the instance with name = bar, and then again first time I received this error. Consecutive attempts succeeded.

**Comment by isurulucky** [comment]
Had a look, and could re-produce in random occasions. Could be due to how we read the command output from the terminal. This error has been noted in the CLI previously as well, and have use a method dump the complete output to a file and then read from it to overcome the issue. Have modified the relevant places to do the same in https://github.com/wso2-cellery/sdk/pull/758. Could not reproduce this afterwards.

**Comment by sinthuja** [comment]
Verified, the error doesn't come any more.
