### ISSUE TITLE
Intermittent error while exporting autoscale policy

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2-cellery/sdk#735]
**Description:**
While trying to export autoscale policy the below error can be observed intermittently. This happened in the very first time and kept working for subsequent tests. GCP complete setup

Hasinthas-MacBook-Pro:pet-fe hasinthaindrajee$ cellery export-policy autoscale cell pet-be
❌ Exporting autoscale policies

Unable to export autoscale policies from instance pet-be: unexpected end of JSON input

Let's add some debug logs to see what goes wrong.

**Comment by isurulucky** [comment]
Had a look, and could re-produce in random occasions. Could be due to how we read the command output from the terminal. This error has been noted in the CLI previously as well, and have use a method dump the complete output to a file and then read from it to overcome the issue. Have modified the relevant places to do the same in #758. Could not reproduce this afterwards.

**Comment by sinthuja** [comment]
Verified, tried several times, and didn't encounter any issues
